.TH BACKUP-MARIADB: "1" "March 2022" "wmfbackups" "User Commands"
.SH NAME
backup-mariadb \- execute local mariadb backups
.SH DESCRIPTION
.PP
Create a mysql/mariadb logical backup using mydumper or a snapshot using
mariabackup. It has 2 modes: interactive, where options are received from the
command line and non\-interactive, where it reads from a config file and
performs several backups
.SH SYNOPSIS
.B backup-mariadb
[\-h] [\-\-config\-file CONFIG_FILE] [\-\-host HOST]
[\-\-port PORT] [\-\-user USER] [\-\-password PASSWORD]
[\-\-threads THREADS] [\-\-type {dump,snapshot}]
[\-\-only\-postprocess] [\-\-rotate] [\-\-retention RETENTION]
[\-\-backup\-dir BACKUP_DIR] [\-\-rows ROWS] [\-\-archive]
[\-\-compress] [\-\-regex REGEX] [\-\-stats\-file STATS_FILE]
[section]
.SS "positional arguments:"
.TP
section
Section name of the backup. E.g.: "s3", "tendril". If
section is set, \fB\-\-config\-file\fR is ignored. If it is
empty, only config\-file options will be used and other
command line options will be ignored. For \fB\-\-only\-postprocess\fR work,
you can also provide an absolute path of the backup directory.
.SS "optional arguments:"
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-\-config\-file\fR CONFIG_FILE
Config file to use. By default,
\fI\,/etc/wmfbackups/backups.cnf\/\fP .
.TP
\fB\-\-host\fR HOST
Host to generate the backup from. Default: localhost.
.TP
\fB\-\-port\fR PORT
Port to connect to. Default: 3306.
.TP
\fB\-\-user\fR USER
User to connect for backup. Default: root.
.TP
\fB\-\-password\fR PASSWORD
Password used to connect. Default: empty password.
.TP
\fB\-\-threads\fR THREADS
Number of threads to use for exporting. Default: 18
concurrent threads.
.TP
\fB\-\-type\fR {dump,snapshot}
Backup type: dump or snapshot. Default: dump
.TP
\fB\-\-only\-postprocess\fR
If present, only postprocess and perform the metadata
gathering metrics for the given ongoing section
backup, skipping the actual backup. Default: Do the
whole process.
.TP
\fB\-\-rotate\fR
If present, run the rotation process, by moving it to
the standard."latest" backup. Default: Do not rotate.
.TP
\fB\-\-retention\fR RETENTION
If rotate is set, purge backups of this section older
than the given value, in days. Default: 18 days.
.TP
\fB\-\-backup\-dir\fR BACKUP_DIR
Directory where the backup will be stored. Default:
\fI\,/srv/backups\/\fP.
.TP
\fB\-\-rows\fR ROWS
Max number of rows to dump per file. Default: 20000000
.TP
\fB\-\-archive\fR
If present, archive each db on its own tar file.
.TP
\fB\-\-compress\fR
If present, compress everything into a tar.gz.Default:
Do not compress.
.TP
\fB\-\-regex\fR REGEX
Only backup tables matching this regular
expression,with format: database.table. Default: all
tables
.TP
\fB\-\-stats\-file\fR STATS_FILE
Separate ini mysql file where the statistics options are
defined in a [client] section. If this option is not given,
statistics will not be gathered.
.SH "SEE ALSO"
Full documentation available at https://wikitech.wikimedia.org/wiki/MariaDB/Backups
See also related command:
.B remote-backup-mariadb
and config file:
.B backups.cnf
.SH AUTHOR
Jaime Crespo
.SH COPYRIGHT
2018-2022, Jaime Crespo <jcrespo@wikimedia.org>, Wikimedia Foundation, Inc.
