wmfmariadbpy/RemoteExecution/__init__.py usr/lib/python3/dist-packages/wmfmariadbpy/RemoteExecution
wmfmariadbpy/RemoteExecution/CuminExecution.py usr/lib/python3/dist-packages/wmfmariadbpy/RemoteExecution
wmfmariadbpy/RemoteExecution/LocalExecution.py usr/lib/python3/dist-packages/wmfmariadbpy/RemoteExecution
wmfmariadbpy/RemoteExecution/RemoteExecution.py usr/lib/python3/dist-packages/wmfmariadbpy/RemoteExecution
