wmfmariadbpy/compare.py usr/lib/python3/dist-packages/wmfmariadbpy
wmfmariadbpy/mysql.py usr/lib/python3/dist-packages/wmfmariadbpy
wmfmariadbpy/osc_host.py usr/lib/python3/dist-packages/wmfmariadbpy
wmfmariadbpy/switchover.py usr/lib/python3/dist-packages/wmfmariadbpy
wmfmariadbpy/replication_tree.py usr/lib/python3/dist-packages/wmfmariadbpy
wmfmariadbpy/move_replica.py usr/lib/python3/dist-packages/wmfmariadbpy
wmfmariadbpy/stop_in_sync.py usr/lib/python3/dist-packages/wmfmariadbpy
usr/bin/db-compare
usr/bin/mysql.py
usr/bin/db-osc-host
usr/bin/db-switchover
usr/bin/db-replication-tree
usr/bin/db-move-replica
usr/bin/db-stop-in-sync
